### PR TITLE
Merge two Awesome Repos

### PR DESCRIPTION
**Pull request by Varunram**
@aloisdg Done!

### CODE REVIEW

**Comment by aloisdg** [comment]
@quobit @hueitan anything to add before merge?

**Comment by Varunram** [comment]
@quobit @hueitan @aloisdg  Anything I have to update on this front?

**Comment by aloisdg** [comment]
@Varunram done :)

**Comment by Varunram** [comment]
Thanks a ton!

**Comment by Varunram** [comment]
I just noticed a closing brace was messing up the styling and changed it via https://github.com/aloisdg/awesome-regex/commit/4f6669a65f2201ebc254c7a8c1f4f15ffe0ee883. (Apologies for not opening a PR, the change was very minimal, so I committed)

**Comment by aloisdg** [comment]
No problem. You are now a collaborator. You have the power, you have the responsibility. Your previous list reveals some dedications. 

@quobit You show a lot of implication in this project. This project need you.

**Comment by quobit** [comment]
Thank you @aloisdg 
_With great power comes great responsibility..._

**Pull request merged**
