### PR TITLE
Added RegexHQ

### PR DESCRIPTION
**Pull request by quobit**
A GitHub Organization whose aim is "_Collaboration on world-wide community-driven collections of RegExp patterns and tools that can make our life easier_"

### CODE REVIEW

**Comment by aloisdg** [comment]
We talked about moving this repo to their organization. They shows some reorganization previously. We decided to postpone and we didn't talk about it since. I am still favorable of a move. I don't really care about the 'ownership' of the project. I just want a place somewhere for the list. Here is fine, but I am willing to change if the list is better there.

What do you think?

**Comment by quobit** [comment]
I don't see details of that talk. Was it via gitter?

**Comment by aloisdg** [comment]
@quobit I dont remember in fact. I thought it was on github's issues (here or there).

**Comment by charlike** [comment]
I don't remember too. But you are welcome to transfer it and i'll invite you there. Purpose of both are same, collection of RegExp things. The only difference is that we collect code, not links and articles. So this list would come as great addition to our purpose (for example as replacement of our current wiki page) :)

I also dream for some cool website with some features, but we need time and interested people.

**Comment by Varunram** [comment]
I'm new here, so I'll just leave my two cents. It would be amazing if we integrate stuff, but I'm not sure how moving works on GitHub. @charlike Do we have to fork or does @aloisdg have to change ownership?

**Comment by charlike** [comment]
@Varunram, it's only needed to transfer this repo from the settings page, yea. nothing more, it is owner decision, I sent him invite to the org, before some long long time

**Comment by Varunram** [comment]
Closing this due to age.

**Comment by tunnckoCore** [comment]
Oooh, yep. It's on @aloisdg :)

**Pull request closed without merging**
