### PR TITLE
Added RegexMagic

### PR DESCRIPTION
**Pull request by quobit**

### CODE REVIEW

**Comment by aloisdg** [comment]
We have to pay for RegexMagic

**Comment by quobit** [comment]
And for all the books in the books section

**Comment by aloisdg** [comment]
Indeed. I didnt read them but the were present in different source around Regex. Are you related to RegexMagic? Do you use it everyday? How it change your workflow?

**Comment by quobit** [comment]
Sorry for answering so late. No, I'm not related to them and I don't use it.

**Comment by aloisdg** [comment]
I am fine with adding paid content if it really worth it. Here I am not sure if it is the case. How would you compare it against free solution like Debuggex/RegExr/Regex101 etc.

**Comment by quobit** [comment]
I didn't tested it (I don't use Windows). I've simply viewed the video section to see the UX. I'm fine if you close the PR.

**Comment by aloisdg** [comment]
I let it open for now, if you dont mind :)

**Comment by Varunram** [comment]
Closing this due to age and the fact that RegexMagic is still a paid product, so we can't test it

**Pull request closed without merging**
