### PR TITLE
Add Python Regex Zero to Hero

### PR DESCRIPTION
**Pull request by alimirferdos**

### CODE REVIEW

**Comment by alimirferdos** [comment]
That's because I've changed the order as said in "Contribution" page to keep the list alphabetically sorted

**Comment by Varunram** [comment]
Yes, but that just requires one line's insertion, which was the change suggested in the initial review :)

**Comment by alimirferdos** [comment]
So I'm gonna make a new pull request

**Comment by alimirferdos** [comment]
I tried to start a new PR in order to follow the suggestion and I used the Github's editor and the result was the same! In order to keep the list sorted as suggested in [this issue](https://github.com/aloisdg/awesome-regex/issues/60#issue-373021962) it works as it is here.
What should I do now? create a new PR without sorting?
The new commit of this PR was because of new PR I was trying to create while keeping the forked repository.

**Comment by Varunram** [comment]
Using Github's editor results in whitespace errors and indentation errors :) You would need to pull the repo locally, add your changes on top and then push to a branch of your fork, after which you can propose a PR.  Please use an editor like vim which does not change indentations or line endings arbitrarily (like some other common editors may be configured to do by default). Feel free to continue this thread and ask help in case you need to, thanks!

**Pull request closed without merging**
