### PR TITLE
Add the page from perl-begin.org.

### PR DESCRIPTION
**Pull request by shlomif**
Note that it is a site I maintain.

### CODE REVIEW

**Comment by shlomif** [comment]
ping.

**Comment by shlomif** [comment]
@aloisdg : hi! ping. Can this be merged?

**Comment by Varunram** [comment]
@shlomif sorry I didn't notice this, merged!

**Comment by shlomif** [comment]
> @shlomif sorry I didn't notice this, merged!

@Varunram : thanks and you are welcome. note that some friends and I wrote a github dashboard - https://github.com/shlomif/github-dashboard .

**Comment by aloisdg** [comment]
This perl-begin.org's entry about regex looks like a collection of links. I think it would be more useful to add directly thoses links to awesome-regex.

Any thoughts?

**Pull request merged**
