### PR TITLE
Add Simple Regex and RegExTranslator.com

### PR DESCRIPTION
**Pull request by corsonknowles**
Tools for translating and composing regex in English

### CODE REVIEW

**Comment by aloisdg** [comment]
Thank you for the submission!

I am not sure about the category though. I will dig it a bit. Any input is welcome.

**Comment by corsonknowles** [comment]
Thanks! I was thinking Prototyping and Test was a fine category, because it can be used to put regular expressions together and see what they do. 

However, a case could also be made for putting it under Documentation, or Generator, or Learning. I think any of the 4 of those would fit it. 

Last case scenario would be to make a new category: Translator. 

What do you think is best?

**Comment by corsonknowles** [comment]
How about Learning?

**Comment by hueitan** [comment]
What about **Explanation**? It explain the regex in English word.

**Comment by corsonknowles** [comment]
Yes, let's go with Explanation. Good choice!

**Pull request merged**
