### PR TITLE
Add Text Generators Section

### PR DESCRIPTION
**Pull request by curious-odd-man**

### CODE REVIEW

**Comment by aloisdg** [comment]
This is a young tool. I like the idea though. Let it grow and we will see to add it.

**Comment by curious-odd-man** [comment]
Hello. I see. But I kindly ask you to reconsider. Adding that library here would greatly help it to grow. Maybe we could still add it with some note? Besides, since that is the first library in a category - it could help a lot of people. If you decide to add it - please tell me, I'll first update documentation to reflect that it is java libaray actually, if not - then nothing.

**Comment by aloisdg** [comment]
I dont know how the other awesome list deals with this kind of issue. I should check for direction. The main idea of the list is to be community-driven instead of being a tool for promotion. As a user of those list, I read them for community-approved content.

That said, I could imagine a specific flag for alerting readers about a young tool. A kind of shout-out but also a warning.

cc @hueitan @quobit @Varunram

**Comment by curious-odd-man** [comment]
Hello again @aloisdg !

At the start - when I've opened you told: 

>  Let it grow and we will see to add it.

Now - some time has passed. I've already gathered some stars and positive download statistics from maven nexus:
image
I've also got only one bug report so far which I closed next day.

How do you think - did my library earned a place in your awesome-list?

Anyway those who you asked - did not respond in any way. So I guess it's up to you.

Wishing all the best,
Vlad

**Pull request closed without merging**
