### PR TITLE
Adding RegExLib site to Library section

### PR DESCRIPTION
**Pull request by quobit**

### CODE REVIEW

**Comment by aloisdg** [comment]
I wonder wether library is the best category for this website.

**Comment by quobit** [comment]
Sorry! You are right. Maybe under Tips & tricks?

**Comment by aloisdg** [comment]
I don't know in fact.

**Comment by huei90** [comment]
I think this "Library" should under Tips n Tricks. This "Library" is not the "Library" we used in the section.

**Comment by aloisdg** [comment]
Ok lets go for this.

**Comment by quobit** [comment]
:+1:

**Pull request merged**
